"""initial_schema

Revision ID: 4e30f48e8c68
Revises: 
Create Date: 2026-02-18 07:57:40.775493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e30f48e8c68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excel_filename', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_requirements', sa.Integer(), nullable=False),
    sa.Column('completed_requirements', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_classification',
    sa.Column('scope_item_prefix', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('module_name_ja', sa.String(length=100), nullable=False),
    sa.Column('business_domain', sa.String(length=100), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scope_item_prefix')
    )
    op.create_table('functional_requirement',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('business_category', sa.String(length=500), nullable=True),
    sa.Column('business_name', sa.String(length=500), nullable=True),
    sa.Column('function_name', sa.String(length=500), nullable=False),
    sa.Column('requirement_summary', sa.Text(), nullable=True),
    sa.Column('requirement_detail', sa.Text(), nullable=True),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('original_row_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping_result',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('functional_requirement_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('judgment_level', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('proposal_text', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('matched_scope_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_retry_count', sa.Integer(), nullable=False),
    sa.Column('search_score', sa.Float(), nullable=True),
    sa.Column('langsmith_trace_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['functional_requirement_id'], ['functional_requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('functional_requirement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapping_result')
    op.drop_table('functional_requirement')
    op.drop_table('module_classification')
    op.drop_table('case')
    # ### end Alembic commands ###
