"""add_rationale_split_fields

Revision ID: 88785c2098b3
Revises: 4e30f48e8c68
Create Date: 2026-02-20 18:41:52.801002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88785c2098b3'
down_revision: Union[str, Sequence[str], None] = '4e30f48e8c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_result', sa.Column('scope_item_analysis', sa.Text(), nullable=True))
    op.add_column('mapping_result', sa.Column('gap_analysis', sa.Text(), nullable=True))
    op.add_column('mapping_result', sa.Column('judgment_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_result', 'judgment_reason')
    op.drop_column('mapping_result', 'gap_analysis')
    op.drop_column('mapping_result', 'scope_item_analysis')
    # ### end Alembic commands ###
